environment:
  matrix:
    - BUILD_TYPE: Debug
      COMPILER: MinGW
      MINGW_BIN: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin'
      ARCH: x64

image:
  - Visual Studio 2015
  # - Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf input
  - cmd: if [%COMPILER%]==[MinGW] SET PATH=%MINGW_BIN%;%PATH:C:\Program Files\Git\usr\bin;=%

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: if [%COMPILER%]==[MSVC] cmake .. -A%ARCH% -DINSTALL_WIN_DEPS=ON
  - cmd: if [%COMPILER%]==[MinGW] cmake .. -G "MinGW Makefiles" -DINSTALL_WIN_DEPS=ON -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin;C:/MinGW/bin"
  - cmd: cmake --build .
  - cmd: if [%COMPILER%]==[MSVC] cmake .. -A%ARCH% -DINSTALL_WIN_DEPS=OFF
  - cmd: if [%COMPILER%]==[MinGW] cmake .. -G "MinGW Makefiles" -DINSTALL_WIN_DEPS=OFF

build_script:
  - cmd: cmake --build . --config Debug

test_script:
  - cmd: ctest build
