environment:
  matrix:
    # - BUILD_TYPE: Debug
      # COMPILER: MSVC
      # ARCH: x64
    - BUILD_TYPE: Debug
      COMPILER: MinGW
      ARCH: x64

os:
  - Visual Studio 2015
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: if [%COMPILER%]==[MSVC] cmake .. -Ax64 -DINSTALL_WIN_DEPS=ON
  - cmd: if [%COMPILER%]==[MinGW] cmake .. -G "MinGW Makefiles" -DCMAKE_SH=CMAKE_SH-NOTFOUND -DINSTALL_WIN_DEPS=ON -DCMAKE_C_COMPILER=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\gcc 
  - cmd: cmake --build .
  - cmd: if [%COMPILER%]==[MSVC] cmake .. -Ax64 -DINSTALL_WIN_DEPS=OFF
  - cmd: if [%COMPILER%]==[MinGW] cmake .. -G "MinGW Makefiles" -DCMAKE_SH=CMAKE_SH-NOTFOUND -DINSTALL_WIN_DEPS=OFF

build_script:
  - cmd: cmake --build . --config Debug

test_script:
  - cmd: ctest build
