os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "Visual Studio 15 Win64" -DINSTALL_WIN_DEPS=ON
  - cmd: cmake --build .
  - cmd: cmake .. -G "Visual Studio 15 Win64" -DINSTALL_WIN_DEPS=OFF

build_script:
  - cmd: cmake --build . --config Debug

test_script:
  - cmd: ctest build
