dist: trusty
sudo: require

language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - clang-3.9
      - cmake
      - libsdl2-dev
      - libglew-dev
      - libsdl2-image-dev

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/clang-3.9 /usr/local/bin/clang
  - gcc -v && cmake --version && clang -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - NPROC=$(nproc)
  - cmake --build . -- --jobs $NPROC
  - ctest . --parallel $NPROC
