dist: trusty
sudo: false

language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libsdl2-dev
      - libglew-dev
      - libsdl2-image-dev

script:
  - gcc -v; cmake --version; clang -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc
  - NPROC=$(nproc)
  - cmake --build . -- --jobs $NPROC
  - ctest . --parallel $NPROC
