dist: trusty
sudo: false

language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsdl2-dev
      - libglew-dev
      - libsdl2-image-dev

script:
  - gcc-7 -v && cmake --version && clang-3.9 -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - NPROC=$(nproc)
  - cmake --build . -- --jobs $NPROC
  - ctest . --parallel $NPROC
