os: linux
dist: trusty
sudo: false

language: c
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-7
      - libsdl2-dev
      - libglew-dev
      - libsdl2-image-dev

script:
  - gcc-7 -v; cmake --version; clang -v
  - export CC=gcc-7
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - NPROC=$(nproc)
  - cmake --build . -- --jobs $NPROC
  - ctest . --parallel $NPROC
