# Travis configurations:
#  - Ubuntu trusty (14.04): gcc and clang
#  - OSX: clang

os: 
  - linux
  - osx
dist: trusty
sudo: false

language: c
compiler:
  - gcc-8
  - clang-3.9
  - clang

# Configure the Ubuntu machine to have all dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - clang-3.9
      - libsdl2-dev
      - libglew-dev
      - libsdl2-image-dev

# We only compile macOS with clang (the default compiler)
matrix:
  exclude:
    - os: osx
      compiler: gcc-8
    - os: osx
      compiler: clang-3.9
    - os: linux
      compiler: clang

env:
  - CONFIG=Release
  - CONFIG=Debug

# Configure OSX to have all dependencies
before_install:
  - if [[ $TRAVIS_OS_NAME = osx ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME = osx ]]; then brew install glew sdl2 sdl2_image; fi

# Build the project
script:
  # What the config we are currently on is doing
  - uname -a; cmake --version; $CC --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG
  - if [[ $TRAVIS_OS_NAME = osx ]]; then NPROC=$(sysctl -n hw.physicalcpu); else NPROC=$(nproc); fi
  - cmake --build . -- --jobs $NPROC
  - ctest . --parallel $NPROC
