os: 
  - linux
  - osx
dist: trusty
sudo: false

language: c
compiler:
  - gcc-7
  - clang-3.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-7
      - clang-3.9
      - libsdl2-dev
      - libglew-dev
      - libsdl2-image-dev

before_install:
  - if [[ $TRAVIS_OS_NAME = osx ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME = osx ]]; then brew install glew sdl2 sdl2_image; fi

script:
  - gcc-7 -v; cmake --version; clang -v
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - NPROC=$(nproc)
  - cmake --build . -- --jobs $NPROC
  - ctest . --parallel $NPROC
